compile:
	g++ -I/usr/lib64/ -lopencv_core -lopencv_highgui -lopencv_imgproc -fopenmp -mavx -mavx2 -mfma -O3 testc.cpp -o testc.x

run:
#	./testc.x 40 80
#	./testc.x 160 320
#	./testc.x 500 1000
#	./testc.x 1600 3200
	./testc.x 3000 6000

clean:
	rm -rf *.x
